import { Platform, StyleSheet } from 'react-native';

import { colors, radius, shadow, spacing } from '@/src/shared/theme';

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  webSlidePage: { flex: 1 },
  content: { gap: spacing.md, paddingHorizontal: spacing.md, paddingTop: spacing.lg, paddingBottom: spacing.xxl },
  logPageContent: { paddingHorizontal: spacing.md },
  bottomSegmentedContent: { paddingBottom: 268 },
  sideSegmentedContent: { paddingBottom: 176 },
  noScrollBounce: Platform.select({
    web: { overscrollBehaviorY: 'none' } as any,
    default: {},
  }),
  card: { backgroundColor: colors.surface, borderRadius: radius.xl, gap: spacing.md, padding: spacing.lg, ...shadow },
  swipeCard: { alignSelf: 'stretch', borderRadius: radius.xl, overflow: 'hidden', position: 'relative', width: '100%' },
  swipeListCard: { borderRadius: 0 },
  swipeRail: { alignItems: 'stretch', flexDirection: 'row', width: '100%' },
  swipeContent: { width: '100%', zIndex: 1 },
  swipeDeleteAction: { alignItems: 'center', alignSelf: 'stretch', backgroundColor: colors.danger, borderBottomRightRadius: radius.xl, borderTopRightRadius: radius.xl, justifyContent: 'center', width: 56 },
  swipeActionPressed: { opacity: 0.88 },
  swipeListDeleteAction: { borderBottomRightRadius: 0, borderTopRightRadius: 0 },
  innerCard: { backgroundColor: colors.surfaceMuted, elevation: 0, shadowOpacity: 0 },
  selectedCard: { borderColor: colors.primary, borderWidth: 1 },
  completedCard: { backgroundColor: colors.successSoft },
  row: { alignItems: 'center', flexDirection: 'row', gap: spacing.md },
  rowTop: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.md, justifyContent: 'space-between' },
  rowWrap: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  modalContent: { padding: spacing.lg, paddingBottom: spacing.xxl },
  iconColumn: { alignItems: 'center', gap: spacing.xs },
  itemTitle: { color: colors.text, fontSize: 18, fontWeight: '700', lineHeight: 24 },
  sectionTitle: { color: colors.text, fontSize: 16, fontWeight: '700', marginBottom: spacing.xs },
  bodyText: { color: colors.textSoft, fontSize: 16, lineHeight: 24, fontWeight: '500' },
  metaText: { color: colors.muted, fontSize: 13, lineHeight: 18, fontWeight: '500' },
  emptyText: { color: colors.muted, fontSize: 14, lineHeight: 20, textAlign: 'center' },
  emojiImage: { width: 32, height: 32 },
  bigEmojiImage: { width: 44, height: 44 },
  timeline: { gap: spacing.lg },
  compactLogTimeline: { gap: spacing.md },
  splitStack: { gap: spacing.lg },
  tagRow: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs },
  tag: { borderRadius: radius.md, overflow: 'hidden', paddingHorizontal: spacing.sm, paddingVertical: 4 },
  tag_gray: { backgroundColor: colors.surfaceMuted, color: colors.textSoft },
  tag_blue: { backgroundColor: colors.primarySoft, color: colors.primary },
  tag_green: { backgroundColor: colors.successSoft, color: colors.success },
  tag_red: { backgroundColor: colors.dangerSoft, color: colors.danger },
  tag_purple: { backgroundColor: '#F3F0FF', color: '#6741D9' },
  tag_orange: { backgroundColor: colors.warningSoft, color: colors.warning },
  staffCard: { backgroundColor: colors.surface },
  staff: { height: 220, position: 'relative' },
  staffCurve: { left: 0, position: 'absolute', top: 0 },
  staffLine: { backgroundColor: colors.border, height: 1, marginTop: 34, opacity: 0.5 },
  staffPoint: { alignItems: 'center', position: 'absolute', width: 42, gap: 4 },
  staffEmoji: { fontSize: 24 },
  staffEmojiImage: { width: 22, height: 22 },
  staffTime: { color: colors.faint, fontSize: 9, textAlign: 'center' },
  moodPicker: { flexDirection: 'row', gap: spacing.sm, justifyContent: 'space-between', marginBottom: spacing.xl },
  moodButton: { flex: 1, alignItems: 'center', backgroundColor: colors.surfaceMuted, borderRadius: radius.xl, paddingVertical: spacing.lg, paddingHorizontal: spacing.xs },
  moodButtonSelected: { backgroundColor: colors.primarySoft, borderColor: colors.primary, borderWidth: 1.5 },
  moodLabel: { color: colors.textSoft, fontSize: 12, fontWeight: '700', marginTop: 8 },
  searchPanel: { alignItems: 'center', backgroundColor: colors.surface, borderRadius: radius.lg, flexDirection: 'row', gap: spacing.sm, marginHorizontal: spacing.lg, marginTop: spacing.sm, minHeight: 42, paddingHorizontal: spacing.md, ...shadow },
  searchInput: { color: colors.text, flex: 1, fontSize: 15, fontWeight: '600', minHeight: 40, paddingHorizontal: 0 },
  teachingTopRow: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.md, marginBottom: spacing.md },
  teachingClassField: { flex: 1.2 },
  teachingRatingField: { flex: 0.95 },
  teachingRatingPills: { flexDirection: 'row', gap: spacing.xs },
  teachingRatingPill: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.xl, borderWidth: 1, paddingHorizontal: spacing.lg, paddingVertical: spacing.sm },
  teachingLogTitleRow: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  teachingLogTitle: { flexShrink: 1, fontSize: 18, lineHeight: 25 },
  teachingLogMeta: { color: colors.muted, fontSize: 14, lineHeight: 20, fontWeight: '500' },
  teachingDetail: { borderRadius: radius.lg, gap: 3, padding: spacing.md },
  teachingDetail_gray: { backgroundColor: colors.surfaceMuted },
  teachingDetail_green: { backgroundColor: '#DCFCE7' },
  teachingDetail_red: { backgroundColor: colors.dangerSoft },
  teachingDetail_blue: { backgroundColor: colors.primarySoft },
  teachingDetailLabel: { color: colors.textSoft, fontSize: 13, fontWeight: '700', lineHeight: 17 },
  teachingDetailValue: { color: colors.textSoft, fontSize: 15, lineHeight: 22, fontWeight: '500' },
  formLabel: { color: colors.textSoft, fontSize: 13, fontWeight: '700', marginBottom: spacing.sm },
  pills: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginBottom: spacing.md },
  pill: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.full, borderWidth: 1, paddingHorizontal: spacing.lg, paddingVertical: spacing.sm },
  pill_large: { minHeight: 48, paddingHorizontal: spacing.xl, paddingVertical: spacing.md },
  pillSelected: { backgroundColor: colors.primarySoft, borderColor: colors.primary },
  pillText: { color: colors.textSoft, fontSize: 13, fontWeight: '700' },
  pillText_large: { fontSize: 15, lineHeight: 20 },
  pillTextSelected: { color: colors.primary },
  miniMood: { alignItems: 'center', borderRadius: radius.full, height: 36, justifyContent: 'center', width: 36 },
  input: { backgroundColor: colors.surfaceMuted, borderRadius: radius.lg, color: colors.text, fontSize: 16, minHeight: 52, paddingHorizontal: spacing.lg },
  textArea: { minHeight: 120, paddingTop: spacing.md },
  formRow: { flexDirection: 'row', gap: spacing.md },
  formActions: { flexDirection: 'row', gap: spacing.md, justifyContent: 'flex-end', marginTop: spacing.xl, paddingBottom: spacing.md },
  group: { gap: spacing.md },
  compactLogGroup: { gap: spacing.sm },
  compactLogCard: { gap: spacing.xs, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderWidth: 1, borderColor: colors.border },
  groupTitle: { color: colors.textSoft, fontSize: 14, fontWeight: '700' },
  detailBlock: { borderTopColor: colors.border, borderTopWidth: 1, gap: spacing.sm, marginTop: spacing.sm, paddingTop: spacing.sm },
  detail: { borderRadius: radius.lg, gap: 2, padding: spacing.md },
  detail_gray: { backgroundColor: colors.surfaceMuted },
  detail_green: { backgroundColor: colors.successSoft },
  detail_red: { backgroundColor: colors.dangerSoft },
  detail_blue: { backgroundColor: colors.primarySoft },
  detailLabel: { color: colors.textSoft, fontSize: 11, fontWeight: '700', lineHeight: 14 },
  detailValue: { color: colors.textSoft, fontSize: 13, lineHeight: 18, fontWeight: '500' },
  statsGrid: { gap: spacing.md },
  statCard: { gap: spacing.xs },
  statLabel: { color: colors.muted, fontSize: 12, fontWeight: '700' },
  statValue: { color: colors.text, fontSize: 24, fontWeight: '600' },
  summaryHero: { backgroundColor: colors.surface, borderRadius: radius.xxl, gap: spacing.lg, padding: spacing.lg, ...shadow },
  summaryHeroTop: { alignItems: 'center', flexDirection: 'row', gap: spacing.md, justifyContent: 'space-between' },
  summaryHeroIcon: { alignItems: 'center', borderRadius: radius.xl, height: 48, justifyContent: 'center', width: 48 },
  summaryHeroLabel: { color: colors.muted, fontSize: 13, fontWeight: '600', lineHeight: 18 },
  summaryHeroValue: { color: colors.text, fontSize: 28, fontWeight: '700', lineHeight: 34 },
  summaryMetricRow: { flexDirection: 'row', gap: spacing.sm },
  summaryMetric: { backgroundColor: colors.surfaceMuted, borderRadius: radius.lg, flex: 1, gap: 2, paddingHorizontal: spacing.md, paddingVertical: spacing.sm },
  summaryMetricLabel: { color: colors.muted, fontSize: 12, fontWeight: '600', lineHeight: 16 },
  summaryMetricValue: { color: colors.text, fontSize: 18, fontWeight: '700', lineHeight: 23 },
  recordCard: { backgroundColor: colors.surface, borderRadius: radius.xl, gap: spacing.sm, paddingHorizontal: spacing.lg, paddingVertical: spacing.md, ...shadow },
  recordIcon: { alignItems: 'center', borderRadius: radius.lg, height: 44, justifyContent: 'center', width: 44 },
  recordTitleRow: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  recordAmount: { color: colors.danger, fontSize: 20, fontWeight: '700', lineHeight: 25 },
  recordRight: { alignItems: 'flex-end', gap: spacing.xs, justifyContent: 'center', marginLeft: spacing.sm },
  recordImage: { backgroundColor: colors.border, borderRadius: radius.lg, height: 156, marginTop: spacing.xs, width: '100%' },
  metricLine: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.md },
  metricValue: { color: colors.text, fontSize: 13, fontWeight: '700' },
  progressTrack: { backgroundColor: colors.surfaceMuted, borderRadius: radius.full, height: 8, overflow: 'hidden' },
  progressFill: { borderRadius: radius.full, height: '100%' },
  readingProgressHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: spacing.xs },
  readingProgressLabel: { color: colors.muted, fontSize: 12, fontWeight: '600', lineHeight: 16 },
  readingProgressValue: { color: colors.textSoft, fontSize: 13, fontWeight: '700', lineHeight: 18 },
  readingProgressPreview: { alignItems: 'center', flexDirection: 'row', gap: spacing.md, marginBottom: spacing.md },
  quickAdd: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm },
  quickInput: { backgroundColor: colors.surface, borderRadius: radius.xl, color: colors.text, flex: 1, fontSize: 15, minHeight: 48, paddingHorizontal: spacing.lg, ...shadow },
  addButton: { alignItems: 'center', backgroundColor: colors.primary, borderRadius: radius.xl, height: 44, justifyContent: 'center', width: 44 },
  checkCircle: { alignItems: 'center', borderColor: colors.border, borderRadius: radius.full, borderWidth: 1.5, height: 22, justifyContent: 'center', width: 22 },
  checkCircleDone: { backgroundColor: colors.primary, borderColor: colors.primary },
  completedText: { color: colors.faint, textDecorationLine: 'line-through' },
  footprintImage: { backgroundColor: colors.border, borderRadius: radius.xl, height: 180, marginTop: spacing.md, width: '100%' },
  footprintNotesInput: { minHeight: 72, paddingTop: spacing.md },
  footprintImageGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs, marginTop: spacing.xs },
  footprintImageTile: { backgroundColor: colors.border, borderRadius: radius.lg, height: 104, overflow: 'hidden', position: 'relative', width: '31.8%' },
  footprintImageTileLarge: { height: 170, width: '100%' },
  footprintImageCountBadge: { alignItems: 'center', backgroundColor: 'rgba(15,23,42,0.72)', borderRadius: radius.full, height: 28, justifyContent: 'center', minWidth: 28, paddingHorizontal: spacing.sm, position: 'absolute', right: 8, top: 8 },
  footprintImageCountText: { color: '#fff', fontSize: 13, fontWeight: '700' },
  imageRemoveButton: { alignItems: 'center', backgroundColor: 'rgba(15,23,42,0.72)', borderRadius: radius.full, height: 26, justifyContent: 'center', position: 'absolute', right: 6, top: 6, width: 26 },
  previewImage: { backgroundColor: colors.border, borderRadius: radius.xl, height: 220, width: '100%' },
  fullImageBackdrop: { alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.9)', flex: 1, justifyContent: 'center', padding: spacing.lg },
  fullImage: { height: '90%', width: '100%' },
  fab: { position: 'absolute', bottom: 96, right: 24, width: 64, height: 64, borderRadius: 32, backgroundColor: colors.primary, ...shadow, zIndex: 100, elevation: 8 },
  fabGradient: { flex: 1, borderRadius: 32, justifyContent: 'center', alignItems: 'center' },
  bottomSheetBg: { backgroundColor: colors.surface, borderRadius: radius.xxl },
  bottomSheetIndicator: { backgroundColor: colors.border, width: 40, height: 4, borderRadius: 2 },
  sheetTitle: { fontSize: 20, fontWeight: '700', color: colors.text },
  sheetHeaderRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.md, justifyContent: 'space-between' },
  sheetDeleteButton: {
    alignItems: 'center',
    borderColor: colors.danger,
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.xs,
    minHeight: 38,
    paddingHorizontal: spacing.md,
  },
  sheetDeleteText: { color: colors.danger, fontSize: 13, fontWeight: '600' },
});
