import { Platform, StyleSheet } from 'react-native';

import { colors, radius, shadow, spacing } from '@/src/shared/theme';

/**
 * 明信片的配色与阴影（首页卡片 + 相册页共用）。
 * 关键词：旅游 / 轻快 / 自由 / 明亮 —— 暖白纸面 + 天空蓝 + 阳光色点缀。
 */
export const postcardColors = {
  paper: '#FFFDF8',
  paperEdge: '#F0E9DC',
  ink: '#23292F',
  inkSoft: '#6B7681',
  inkFaint: '#9AA4AE',
  sky: '#EAF4FF',
  skyDeep: '#CFE6FF',
  sun: '#E9A73C',
  sunSoft: '#FDF3E0',
  coral: '#FF7A59',
  mint: '#35B79A',
  grape: '#8B7BE8',
};

export const postcardShadow = {
  elevation: 4,
  shadowColor: '#23292F',
  shadowOffset: { height: 10, width: 0 },
  shadowOpacity: 0.1,
  shadowRadius: 13,
};

export const postcardShadowSoft = {
  elevation: 2,
  shadowColor: '#23292F',
  shadowOffset: { height: 4, width: 0 },
  shadowOpacity: 0.07,
  shadowRadius: 12,
};

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  webSlidePage: { flex: 1 },
  content: { gap: spacing.md, paddingHorizontal: spacing.md, paddingTop: spacing.lg, paddingBottom: spacing.xxl },
  logPageContent: { paddingHorizontal: spacing.md },
  bottomSegmentedContent: { paddingBottom: 268 },
  sideSegmentedContent: { paddingBottom: 176 },
  noScrollBounce: Platform.select({
    web: { overscrollBehaviorY: 'none' } as any,
    default: {},
  }),
  card: { backgroundColor: colors.surface, borderRadius: radius.xl, gap: spacing.md, padding: spacing.lg, ...shadow },
  swipeCard: { alignSelf: 'stretch', borderRadius: radius.xl, overflow: 'hidden', position: 'relative', width: '100%' },
  swipeListCard: { borderRadius: 0 },
  swipeRail: { alignItems: 'stretch', flexDirection: 'row', width: '100%' },
  swipeContent: { width: '100%', zIndex: 1 },
  swipeDeleteAction: { alignItems: 'center', alignSelf: 'stretch', backgroundColor: colors.danger, borderBottomRightRadius: radius.xl, borderTopRightRadius: radius.xl, justifyContent: 'center', width: 56 },
  swipeActionPressed: { opacity: 0.88 },
  swipeListDeleteAction: { borderBottomRightRadius: 0, borderTopRightRadius: 0 },
  innerCard: { backgroundColor: colors.surfaceMuted, elevation: 0, shadowOpacity: 0 },
  selectedCard: { borderColor: colors.primary, borderWidth: 1 },
  completedCard: { backgroundColor: colors.successSoft },
  row: { alignItems: 'center', flexDirection: 'row', gap: spacing.md },
  rowTop: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.md, justifyContent: 'space-between' },
  rowWrap: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  modalContent: { padding: spacing.lg, paddingBottom: spacing.xxl },
  iconColumn: { alignItems: 'center', gap: spacing.xs },
  itemTitle: { color: colors.text, fontSize: 18, fontWeight: '700', lineHeight: 24 },
  sectionTitle: { color: colors.text, fontSize: 16, fontWeight: '700', marginBottom: spacing.xs },
  bodyText: { color: colors.textSoft, fontSize: 16, lineHeight: 24, fontWeight: '500' },
  metaText: { color: colors.muted, fontSize: 13, lineHeight: 18, fontWeight: '500' },
  emptyText: { color: colors.muted, fontSize: 14, lineHeight: 20, textAlign: 'center' },
  emojiImage: { width: 32, height: 32 },
  bigEmojiImage: { width: 44, height: 44 },
  timeline: { gap: spacing.lg },
  compactLogTimeline: { gap: spacing.md },
  splitStack: { gap: spacing.lg },
  tagRow: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs },
  tag: { borderRadius: radius.md, overflow: 'hidden', paddingHorizontal: spacing.sm, paddingVertical: 4 },
  tag_gray: { backgroundColor: colors.surfaceMuted, color: colors.textSoft },
  tag_blue: { backgroundColor: colors.primarySoft, color: colors.primary },
  tag_green: { backgroundColor: colors.successSoft, color: colors.success },
  tag_red: { backgroundColor: colors.dangerSoft, color: colors.danger },
  tag_purple: { backgroundColor: '#F3F0FF', color: '#6741D9' },
  tag_orange: { backgroundColor: colors.warningSoft, color: colors.warning },
  staffCard: { backgroundColor: colors.surface },
  staff: { height: 220, position: 'relative' },
  staffCurve: { left: 0, position: 'absolute', top: 0 },
  staffLine: { backgroundColor: colors.border, height: 1, marginTop: 34, opacity: 0.5 },
  staffPoint: { alignItems: 'center', position: 'absolute', width: 42, gap: 4 },
  staffEmoji: { fontSize: 24 },
  staffEmojiImage: { width: 22, height: 22 },
  staffTime: { color: colors.faint, fontSize: 9, textAlign: 'center' },
  moodPicker: { flexDirection: 'row', gap: spacing.sm, justifyContent: 'space-between', marginBottom: spacing.xl },
  moodButton: { flex: 1, alignItems: 'center', backgroundColor: colors.surfaceMuted, borderRadius: radius.xl, paddingVertical: spacing.lg, paddingHorizontal: spacing.xs },
  moodButtonSelected: { backgroundColor: colors.primarySoft, borderColor: colors.primary, borderWidth: 1.5 },
  moodLabel: { color: colors.textSoft, fontSize: 12, fontWeight: '700', marginTop: 8 },
  searchPanel: { alignItems: 'center', backgroundColor: colors.surface, borderRadius: radius.lg, flexDirection: 'row', gap: spacing.sm, marginHorizontal: spacing.lg, marginTop: spacing.sm, minHeight: 42, paddingHorizontal: spacing.md, ...shadow },
  searchInput: { color: colors.text, flex: 1, fontSize: 15, fontWeight: '600', minHeight: 40, paddingHorizontal: 0 },
  teachingTopRow: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.md, marginBottom: spacing.md },
  teachingClassField: { flex: 1.2 },
  teachingRatingField: { flex: 0.95 },
  teachingRatingPills: { flexDirection: 'row', gap: spacing.xs },
  teachingRatingPill: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.xl, borderWidth: 1, paddingHorizontal: spacing.lg, paddingVertical: spacing.sm },
  teachingLogTitleRow: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  teachingLogTitle: { flexShrink: 1, fontSize: 18, lineHeight: 25 },
  teachingLogMeta: { color: colors.muted, fontSize: 14, lineHeight: 20, fontWeight: '500' },
  teachingDetail: { borderRadius: radius.lg, gap: 3, padding: spacing.md },
  teachingDetail_gray: { backgroundColor: colors.surfaceMuted },
  teachingDetail_green: { backgroundColor: '#DCFCE7' },
  teachingDetail_red: { backgroundColor: colors.dangerSoft },
  teachingDetail_blue: { backgroundColor: colors.primarySoft },
  teachingDetailLabel: { color: colors.textSoft, fontSize: 13, fontWeight: '700', lineHeight: 17 },
  teachingDetailValue: { color: colors.textSoft, fontSize: 15, lineHeight: 22, fontWeight: '500' },
  formLabel: { color: colors.textSoft, fontSize: 13, fontWeight: '700', marginBottom: spacing.sm },
  pills: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginBottom: spacing.md },
  pill: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.full, borderWidth: 1, paddingHorizontal: spacing.lg, paddingVertical: spacing.sm },
  pill_large: { minHeight: 48, paddingHorizontal: spacing.xl, paddingVertical: spacing.md },
  pillSelected: { backgroundColor: colors.primarySoft, borderColor: colors.primary },
  pillText: { color: colors.textSoft, fontSize: 13, fontWeight: '700' },
  pillText_large: { fontSize: 15, lineHeight: 20 },
  pillTextSelected: { color: colors.primary },
  miniMood: { alignItems: 'center', borderRadius: radius.full, height: 36, justifyContent: 'center', width: 36 },
  input: { backgroundColor: colors.surfaceMuted, borderRadius: radius.lg, color: colors.text, fontSize: 16, minHeight: 52, paddingHorizontal: spacing.lg },
  textArea: { minHeight: 120, paddingTop: spacing.md },
  formRow: { flexDirection: 'row', gap: spacing.md },
  formActions: { flexDirection: 'row', gap: spacing.md, justifyContent: 'flex-end', marginTop: spacing.xl, paddingBottom: spacing.md },
  group: { gap: spacing.md },
  compactLogGroup: { gap: spacing.sm },
  compactLogCard: { gap: spacing.xs, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderWidth: 1, borderColor: colors.border },
  groupTitle: { color: colors.textSoft, fontSize: 14, fontWeight: '700' },
  detailBlock: { borderTopColor: colors.border, borderTopWidth: 1, gap: spacing.sm, marginTop: spacing.sm, paddingTop: spacing.sm },
  detail: { borderRadius: radius.lg, gap: 2, padding: spacing.md },
  detail_gray: { backgroundColor: colors.surfaceMuted },
  detail_green: { backgroundColor: colors.successSoft },
  detail_red: { backgroundColor: colors.dangerSoft },
  detail_blue: { backgroundColor: colors.primarySoft },
  detailLabel: { color: colors.textSoft, fontSize: 11, fontWeight: '700', lineHeight: 14 },
  detailValue: { color: colors.textSoft, fontSize: 13, lineHeight: 18, fontWeight: '500' },
  statsGrid: { gap: spacing.md },
  statCard: { gap: spacing.xs },
  statLabel: { color: colors.muted, fontSize: 12, fontWeight: '700' },
  statValue: { color: colors.text, fontSize: 24, fontWeight: '600' },
  summaryHero: { backgroundColor: colors.surface, borderRadius: radius.xxl, gap: spacing.lg, padding: spacing.lg, ...shadow },
  summaryHeroTop: { alignItems: 'center', flexDirection: 'row', gap: spacing.md, justifyContent: 'space-between' },
  summaryHeroIcon: { alignItems: 'center', borderRadius: radius.xl, height: 48, justifyContent: 'center', width: 48 },
  summaryHeroLabel: { color: colors.muted, fontSize: 13, fontWeight: '600', lineHeight: 18 },
  summaryHeroValue: { color: colors.text, fontSize: 28, fontWeight: '700', lineHeight: 34 },
  summaryMetricRow: { flexDirection: 'row', gap: spacing.sm },
  summaryMetric: { backgroundColor: colors.surfaceMuted, borderRadius: radius.lg, flex: 1, gap: 2, paddingHorizontal: spacing.md, paddingVertical: spacing.sm },
  summaryMetricLabel: { color: colors.muted, fontSize: 12, fontWeight: '600', lineHeight: 16 },
  summaryMetricValue: { color: colors.text, fontSize: 18, fontWeight: '700', lineHeight: 23 },
  recordCard: { backgroundColor: colors.surface, borderRadius: radius.xl, gap: spacing.sm, paddingHorizontal: spacing.lg, paddingVertical: spacing.md, ...shadow },
  // ---- 明信片视觉（首页卡片 + 相册页共用）----
  // 设计语言：照片是主角、留白是"纸"、日期是邮戳、标签是贴纸。
  postcardCard: {
    backgroundColor: postcardColors.paper,
    borderColor: postcardColors.paperEdge,
    borderRadius: 24,
    borderWidth: 1,
    paddingBottom: 14,
    paddingHorizontal: 10,
    paddingTop: 10,
    ...postcardShadow,
  },
  postcardPhotoRow: { flexDirection: 'row', gap: 8 },
  postcardPhotoMain: { borderRadius: 16, flex: 1, height: 196, overflow: 'hidden' },
  postcardPhotoFull: { borderRadius: 16, height: 196, overflow: 'hidden', width: '100%' },
  postcardPhotoSide: { flexDirection: 'column', gap: 8, width: 86 },
  postcardPhotoSideCell: { borderRadius: 12, flex: 1, overflow: 'hidden' },
  // 只有两张照片时右侧是一条右上角方形缩略图，不拉成长条
  postcardPhotoSideSquare: { aspectRatio: 1, borderRadius: 12, overflow: 'hidden', width: 86 },
  postcardNoteCount: {
    alignItems: 'center',
    backgroundColor: 'rgba(18,24,32,0.62)',
    borderRadius: 999,
    bottom: 8,
    height: 24,
    justifyContent: 'center',
    minWidth: 36,
    paddingHorizontal: 8,
    position: 'absolute',
    right: 8,
  },
  postcardNoteCountText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  postcardSyncBadge: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 999,
    flexDirection: 'row',
    gap: 4,
    height: 26,
    left: 12,
    paddingHorizontal: 9,
    position: 'absolute',
    top: 12,
  },
  postcardSyncText: { color: '#B4761B', fontSize: 11.5, fontWeight: '700' },
  // 邮戳：虚线圆 + 月·日 + 城市，压在照片右上角
  postcardStamp: {
    alignItems: 'center',
    borderColor: 'rgba(255,255,255,0.85)',
    borderRadius: 999,
    borderStyle: 'dashed',
    borderWidth: 2,
    height: 74,
    justifyContent: 'center',
    position: 'absolute',
    right: 12,
    top: 12,
    transform: [{ rotate: '-11deg' }],
    width: 74,
  },
  postcardStampDay: { color: '#fff', fontSize: 15, fontWeight: '800', lineHeight: 18, textShadowColor: 'rgba(0,0,0,0.35)', textShadowOffset: { height: 1, width: 0 }, textShadowRadius: 4 },
  postcardStampCity: { color: 'rgba(255,255,255,0.92)', fontSize: 10, fontWeight: '700', letterSpacing: 1.2, marginTop: 1, textShadowColor: 'rgba(0,0,0,0.35)', textShadowOffset: { height: 1, width: 0 }, textShadowRadius: 4 },
  postcardBody: { paddingHorizontal: 6, paddingTop: 14 },
  postcardPlaceRow: { alignItems: 'baseline', flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  postcardPlace: { color: postcardColors.ink, flexShrink: 1, fontSize: 21, fontWeight: '800', letterSpacing: -0.2, lineHeight: 26 },
  postcardCityRow: { alignItems: 'center', flexDirection: 'row', gap: 3 },
  postcardCity: { color: postcardColors.sun, fontSize: 13, fontWeight: '700' },
  postcardNote: { color: postcardColors.inkSoft, fontSize: 13, lineHeight: 20, marginTop: 5 },
  // 明信片的"地址线"：iOS 上 borderStyle: 'dashed' 不稳定，改成一条条画出来
  postcardRule: { marginBottom: 10, marginHorizontal: 6, marginTop: 12 },
  postcardRuleDashes: { flexDirection: 'row', gap: 4 },
  postcardRuleDash: { backgroundColor: 'rgba(35,41,47,0.14)', borderRadius: 1, flex: 1, height: 1.5 },
  postcardFoot: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 6 },
  postcardChips: { flexDirection: 'row', flexShrink: 1, flexWrap: 'wrap', gap: 6 },
  postcardChip: { alignItems: 'center', borderRadius: 8, flexDirection: 'row', gap: 5, height: 24, paddingHorizontal: 9 },
  postcardChipText: { fontSize: 11.5, fontWeight: '700' },
  postcardChipDot: { borderRadius: 999, height: 6, width: 6 },
  postcardDate: { color: postcardColors.inkFaint, fontFamily: 'Menlo', fontSize: 11.5, letterSpacing: 0.5 },
  // 无照片：票根
  postcardTicket: {
    backgroundColor: postcardColors.paper,
    borderColor: postcardColors.paperEdge,
    borderRadius: 24,
    borderWidth: 1,
    overflow: 'hidden',
    padding: 16,
    ...postcardShadow,
  },
  // 票根左右两个半圆撕口（颜色 = 页面底色，形成"咬掉一口"的错觉）
  postcardTicketNotch: {
    backgroundColor: '#F8F9FA',
    borderRadius: 999,
    height: 22,
    marginTop: -11,
    position: 'absolute',
    top: '50%',
    width: 22,
  },
  postcardTicketStamp: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.6)',
    borderColor: 'rgba(35,41,47,0.18)',
    borderRadius: 8,
    borderStyle: 'dashed',
    borderWidth: 2,
    height: 88,
    justifyContent: 'center',
    width: 74,
  },
  postcardTicketStampText: { color: postcardColors.inkFaint, fontSize: 10, lineHeight: 14, textAlign: 'center' },
  postcardTicketHint: { color: postcardColors.inkFaint, flex: 1, fontSize: 12, lineHeight: 18 },
  postcardTicketRow: { alignItems: 'flex-start', flexDirection: 'row', gap: 14, padding: 6 },
  // 首页头部：天空渐变 + 大数字 + 指南针
  postcardHeroBlock: {
    marginHorizontal: -spacing.md,
    marginTop: -spacing.lg,
    paddingBottom: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.lg,
  },
  postcardHeroGradient: { height: 250, left: 0, position: 'absolute', right: 0, top: 0 },
  postcardHeroTop: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 2 },
  postcardHeroLabel: { color: '#7A8B9C', fontSize: 12, fontWeight: '700', letterSpacing: 1.6 },
  postcardHeroValueRow: { alignItems: 'baseline', flexDirection: 'row', gap: 6, marginTop: 2 },
  postcardHeroValue: { color: postcardColors.ink, fontSize: 30, fontWeight: '800', letterSpacing: -0.5 },
  postcardHeroUnit: { color: postcardColors.inkFaint, fontSize: 14, fontWeight: '700' },
  postcardHeroIcon: { alignItems: 'center', borderRadius: 16, height: 46, justifyContent: 'center', width: 46, ...postcardShadow },
  postcardSearch: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 23,
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: 14,
    minHeight: 46,
    paddingHorizontal: spacing.lg,
    ...postcardShadowSoft,
  },
  postcardSearchInput: { color: postcardColors.ink, flex: 1, fontSize: 14.5, fontWeight: '600', minHeight: 44, paddingHorizontal: 0 },
  postcardPills: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
  postcardPill: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(35,41,47,0.07)',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    height: 30,
    paddingHorizontal: 13,
  },
  postcardPillSelected: { backgroundColor: postcardColors.ink, borderColor: postcardColors.ink },
  postcardPillText: { color: postcardColors.inkSoft, fontSize: 12.5, fontWeight: '700' },
  postcardPillTextSelected: { color: '#FFFFFF' },
  postcardPillDot: { borderRadius: 999, height: 7, width: 7 },
  // 相册页：拍立得照片墙
  albumHeroBlock: { paddingHorizontal: spacing.md, paddingTop: spacing.sm },
  albumHeroRow: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.md },
  albumHeroInfo: { flex: 1 },
  albumHeroTitle: { color: postcardColors.ink, fontSize: 26, fontWeight: '800', letterSpacing: -0.4, lineHeight: 32 },
  albumHeroCity: { alignItems: 'center', flexDirection: 'row', gap: 4, marginTop: 5 },
  albumHeroCityText: { color: postcardColors.sun, fontSize: 13, fontWeight: '700' },
  albumHeroTags: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 14 },
  albumStamp: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.55)',
    borderColor: 'rgba(35,41,47,0.28)',
    borderRadius: 999,
    borderStyle: 'dashed',
    borderWidth: 2,
    height: 84,
    justifyContent: 'center',
    transform: [{ rotate: '-9deg' }],
    width: 84,
  },
  albumStampYear: { color: '#5A6672', fontFamily: 'Menlo', fontSize: 10, letterSpacing: 2 },
  albumStampDay: { color: '#3F4853', fontSize: 19, fontWeight: '800', lineHeight: 22 },
  albumStampCity: { color: '#8A949E', fontFamily: 'Menlo', fontSize: 9, letterSpacing: 1.4 },
  albumNoteCard: {
    backgroundColor: postcardColors.paper,
    borderColor: postcardColors.paperEdge,
    borderRadius: 20,
    borderWidth: 1,
    marginHorizontal: spacing.md,
    marginTop: spacing.lg,
    paddingBottom: 14,
    paddingLeft: 18,
    paddingRight: 16,
    paddingTop: 14,
    ...postcardShadowSoft,
  },
  albumNoteBar: { backgroundColor: postcardColors.skyDeep, borderRadius: 3, bottom: 14, left: 8, position: 'absolute', top: 14, width: 3 },
  albumNoteText: { color: '#3F4853', fontSize: 14, lineHeight: 24, paddingLeft: 8 },
  albumNoteSign: { color: postcardColors.inkFaint, fontFamily: 'Menlo', fontSize: 11, letterSpacing: 0.5, marginTop: 6, paddingLeft: 8 },
  albumWallHead: { alignItems: 'baseline', flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: spacing.md, paddingBottom: 10, paddingTop: spacing.lg },
  albumWallTitle: { color: postcardColors.ink, fontSize: 15, fontWeight: '800' },
  albumWallCount: { color: postcardColors.inkFaint, fontFamily: 'Menlo', fontSize: 12 },
  albumWallItem: { flex: 1, marginBottom: 14 },
  albumPolaroid: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(35,41,47,0.05)',
    borderRadius: 10,
    borderWidth: 1,
    padding: 8,
    paddingBottom: 0,
    ...postcardShadow,
  },
  albumPolaroidImage: { aspectRatio: 1, borderRadius: 4, overflow: 'hidden', width: '100%' },
  albumPolaroidCap: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingBottom: 9, paddingHorizontal: 2, paddingTop: 7 },
  albumPolaroidTime: { color: '#8A949E', fontFamily: 'Menlo', fontSize: 10.5, letterSpacing: 0.5 },
  albumPolaroidIndex: { color: '#C3CAD1', fontSize: 10, fontWeight: '700' },
  albumTiltLeft: { transform: [{ rotate: '-1.3deg' }] },
  albumTiltRight: { transform: [{ rotate: '1.1deg' }] },
  albumToolbar: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: spacing.md,
    marginTop: spacing.sm,
    paddingHorizontal: 14,
    paddingVertical: 12,
    ...postcardShadowSoft,
  },
  albumToolbarTitle: { color: postcardColors.ink, fontSize: 14, fontWeight: '800' },
  albumToolbarSub: { color: postcardColors.inkSoft, fontSize: 12, marginTop: 2 },
  // 记录 / 编辑足迹页：明信片填写页
  editPreviewWrap: { position: 'relative' },
  editPreviewFrame: {
    alignItems: 'center',
    borderColor: 'rgba(35,41,47,0.18)',
    borderRadius: 16,
    borderStyle: 'dashed',
    borderWidth: 2,
    height: 150,
    justifyContent: 'center',
  },
  editPreviewFrameText: { color: postcardColors.inkFaint, fontSize: 13, fontWeight: '700', marginTop: 6 },
  // 编辑页的明信片预览比列表卡片矮一点（150 高），给下面的表单留位置
  editPhotoFull: { borderRadius: 16, height: 150, overflow: 'hidden', width: '100%' },
  editPhotoMain: { borderRadius: 16, flex: 1, height: 150, overflow: 'hidden' },
  editLiveHint: { color: postcardColors.inkFaint, fontSize: 11.5, marginTop: 8, textAlign: 'center' },
  editLiveHintStrong: { color: postcardColors.sun, fontWeight: '800' },
  editFormCard: {
    backgroundColor: postcardColors.paper,
    borderColor: postcardColors.paperEdge,
    borderRadius: 24,
    borderWidth: 1,
    marginTop: 14,
    paddingBottom: 16,
    paddingHorizontal: 16,
    paddingTop: 2,
    ...postcardShadowSoft,
  },
  editGroup: { paddingBottom: 12, paddingTop: 12 },
  editGroupLabel: { color: postcardColors.inkFaint, fontSize: 11.5, fontWeight: '800', letterSpacing: 1.2 },
  editGroupDivider: { backgroundColor: 'rgba(35,41,47,0.06)', height: 1 },
  editTagRow: {
    alignItems: 'center',
    borderBottomColor: 'rgba(35,41,47,0.10)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 6,
    minHeight: 40,
    paddingBottom: 8,
  },
  editTagChip: { alignItems: 'center', borderRadius: 9, flexDirection: 'row', gap: 5, height: 26, paddingHorizontal: 9 },
  editTagChipText: { fontSize: 12, fontWeight: '700' },
  editTagChipRemove: { fontSize: 13, fontWeight: '700', opacity: 0.55 },
  editTagInput: { color: postcardColors.ink, flexGrow: 1, fontSize: 15, fontWeight: '600', minWidth: 90, padding: 0 },
  editNoteCard: {
    backgroundColor: postcardColors.paper,
    borderColor: postcardColors.paperEdge,
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 8,
    paddingBottom: 10,
    paddingLeft: 18,
    paddingRight: 12,
    paddingTop: 12,
    ...postcardShadowSoft,
  },
  editNoteBar: { backgroundColor: postcardColors.skyDeep, borderRadius: 3, bottom: 12, left: 8, position: 'absolute', top: 12, width: 3 },
  editNoteInput: { color: '#3F4853', fontSize: 13.5, lineHeight: 22, minHeight: 60, padding: 0, textAlignVertical: 'top' },
  editNoteSign: { color: postcardColors.inkFaint, fontFamily: 'Menlo', fontSize: 11, letterSpacing: 0.5, marginTop: 6 },
  editThumbStrip: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10 },
  editThumb: { borderRadius: 14, height: 66, overflow: 'hidden', width: 66 },
  editThumbRemove: {
    alignItems: 'center',
    backgroundColor: 'rgba(15,23,42,0.66)',
    borderRadius: 999,
    height: 18,
    justifyContent: 'center',
    position: 'absolute',
    right: 3,
    top: 3,
    width: 18,
  },
  editThumbAdd: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.5)',
    borderColor: 'rgba(35,41,47,0.18)',
    borderRadius: 14,
    borderStyle: 'dashed',
    borderWidth: 2,
    height: 66,
    justifyContent: 'center',
    width: 66,
  },
  editAddPhoto: {
    alignItems: 'center',
    backgroundColor: postcardColors.sunSoft,
    borderRadius: 23,
    flexDirection: 'row',
    gap: 8,
    height: 46,
    justifyContent: 'center',
    marginTop: 10,
  },
  editAddPhotoText: { color: '#9A6A15', fontSize: 14, fontWeight: '800' },
  editSendOverlay: { alignItems: 'center', bottom: 0, justifyContent: 'center', left: 0, position: 'absolute', right: 0, top: 0 },
  editSendStamp: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,253,248,0.94)',
    borderColor: postcardColors.sun,
    borderRadius: 999,
    borderStyle: 'dashed',
    borderWidth: 2,
    height: 104,
    justifyContent: 'center',
    width: 104,
    ...postcardShadow,
  },
  editSendStampText: { color: '#9A6A15', fontSize: 13, fontWeight: '800', letterSpacing: 1, marginTop: 2 },
  albumEmptyCard: {
    alignItems: 'center',
    borderRadius: 22,
    marginHorizontal: spacing.md,
    marginTop: spacing.lg,
    padding: 22,
    ...postcardShadowSoft,
  },
  recordIcon: { alignItems: 'center', borderRadius: radius.lg, height: 44, justifyContent: 'center', width: 44 },
  // 足迹卡片：标题与城市同一行、日期与标签同一行，避免一行行叠高
  recordCardHeader: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm },
  recordCardIcon: { alignItems: 'center', borderRadius: radius.md, height: 34, justifyContent: 'center', width: 34 },
  recordCardTitleRow: { alignItems: 'baseline', flex: 1, flexDirection: 'row', gap: 6, minWidth: 0 },
  recordCardTitle: { color: colors.text, flexShrink: 1, fontSize: 17, fontWeight: '700', lineHeight: 22 },
  recordCardDot: { color: colors.faint, fontSize: 13, fontWeight: '600' },
  recordCardCoordinate: { color: colors.textSoft, flexShrink: 1, fontSize: 13, fontWeight: '600' },
  recordCardMeta: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  tagCompact: { paddingHorizontal: 6, paddingVertical: 1 },
  recordTitleRow: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  recordAmount: { color: colors.danger, fontSize: 20, fontWeight: '700', lineHeight: 25 },
  recordRight: { alignItems: 'flex-end', gap: spacing.xs, justifyContent: 'center', marginLeft: spacing.sm },
  recordImage: { backgroundColor: colors.border, borderRadius: radius.lg, height: 156, marginTop: spacing.xs, width: '100%' },
  metricLine: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.md },
  metricValue: { color: colors.text, fontSize: 13, fontWeight: '700' },
  progressTrack: { backgroundColor: colors.surfaceMuted, borderRadius: radius.full, height: 8, overflow: 'hidden' },
  progressFill: { borderRadius: radius.full, height: '100%' },
  readingProgressHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: spacing.xs },
  readingProgressLabel: { color: colors.muted, fontSize: 12, fontWeight: '600', lineHeight: 16 },
  readingProgressValue: { color: colors.textSoft, fontSize: 13, fontWeight: '700', lineHeight: 18 },
  readingProgressPreview: { alignItems: 'center', flexDirection: 'row', gap: spacing.md, marginBottom: spacing.md },
  quickAdd: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm },
  quickInput: { backgroundColor: colors.surface, borderRadius: radius.xl, color: colors.text, flex: 1, fontSize: 15, minHeight: 48, paddingHorizontal: spacing.lg, ...shadow },
  addButton: { alignItems: 'center', backgroundColor: colors.primary, borderRadius: radius.xl, height: 44, justifyContent: 'center', width: 44 },
  checkCircle: { alignItems: 'center', borderColor: colors.border, borderRadius: radius.full, borderWidth: 1.5, height: 22, justifyContent: 'center', width: 22 },
  checkCircleDone: { backgroundColor: colors.primary, borderColor: colors.primary },
  completedText: { color: colors.faint, textDecorationLine: 'line-through' },
  footprintImage: { backgroundColor: colors.border, borderRadius: radius.xl, height: 180, marginTop: spacing.md, width: '100%' },
  footprintNotesInput: { minHeight: 72, paddingTop: spacing.md },
  footprintImageGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs, marginTop: spacing.xs },
  footprintImageTile: { backgroundColor: colors.border, borderRadius: radius.lg, height: 104, overflow: 'hidden', position: 'relative', width: '31.8%' },
  pendingBadge: { alignItems: 'center', backgroundColor: colors.warningSoft, borderRadius: radius.full, flexDirection: 'row', gap: 3, paddingHorizontal: 6, paddingVertical: 1 },
  pendingBadgeText: { color: colors.warning, fontSize: 11, fontWeight: '700' },
  footprintImageTileLarge: { height: 170, width: '100%' },
  footprintImageCountBadge: { alignItems: 'center', backgroundColor: 'rgba(15,23,42,0.72)', borderRadius: radius.full, height: 28, justifyContent: 'center', minWidth: 28, paddingHorizontal: spacing.sm, position: 'absolute', right: 8, top: 8 },
  footprintImageCountText: { color: '#fff', fontSize: 13, fontWeight: '700' },
  imageRemoveButton: { alignItems: 'center', backgroundColor: 'rgba(15,23,42,0.72)', borderRadius: radius.full, height: 26, justifyContent: 'center', position: 'absolute', right: 6, top: 6, width: 26 },
  previewImage: { backgroundColor: colors.border, borderRadius: radius.xl, height: 220, width: '100%' },
  fullImageBackdrop: { alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.9)', flex: 1, justifyContent: 'center', padding: spacing.lg },
  fullImage: { height: '90%', width: '100%' },
  fab: { position: 'absolute', bottom: 96, right: 24, width: 64, height: 64, borderRadius: 32, backgroundColor: colors.primary, ...shadow, zIndex: 100, elevation: 8 },
  fabGradient: { flex: 1, borderRadius: 32, justifyContent: 'center', alignItems: 'center' },
  bottomSheetBg: { backgroundColor: colors.surface, borderRadius: radius.xxl },
  bottomSheetIndicator: { backgroundColor: colors.border, width: 40, height: 4, borderRadius: 2 },
  sheetTitle: { fontSize: 20, fontWeight: '700', color: colors.text },
  sheetHeaderRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.md, justifyContent: 'space-between' },
  sheetDeleteButton: {
    alignItems: 'center',
    borderColor: colors.danger,
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.xs,
    minHeight: 38,
    paddingHorizontal: spacing.md,
  },
  sheetDeleteText: { color: colors.danger, fontSize: 13, fontWeight: '600' },
});
